### ISSUE TITLE
Speaker selection via script or service?

### ISSUE THREAD

**Issue by pmcelreavy** [tprelog/homeassistant-gmusic_player#4]
Is there a way to select the speakers via script or a service?

**Comment by tprelog** [comment]
An example to select speakers named `kitchen_stereo` from the service page in HA would look like this.

![image](https://user-images.githubusercontent.com/35702532/65779477-d116b580-e115-11e9-99af-a8d4b6f2968e.png)

----
User @phreaq in the HA form also shared his solution to select speakers using Node Red.

![image](https://user-images.githubusercontent.com/35702532/65779632-1e932280-e116-11e9-8b9e-f2e173f2a49d.png)

**Comment by pmcelreavy** [comment]
Thank you.
Now, we have different accounts, is it possible to setup multiple accounts or multiple gmusic instances?

**Comment by tprelog** [comment]
>Now, we have different accounts, is it possible to setup multiple accounts or multiple gmusic instances?

This I am not sure about. I think it is not likely at this time since these are things I need to add to gmusic. I would hope to eventually re-write this to be a true custom component supporting all HA has to offer including multiple accounts and configuration from GUI but I fear that may be the distant future. You see I am not a programmer by any means. Honestly my only initial intention was just trying to keep the original gmusic switch working. I never thought I would even get this far. So bottom line is, getting gmusic to work in HA is my first attempt at any Object Oriented Programming, learning Python general and creating a custom component for HA. I'm also not the smartest, so learning all these things from the internet is a slow for me. 

I do want to keep working and moving forward with this, I just can't do it as quick as I would like

**Comment by boomshkr** [comment]
Thanks for this wonderfully working component @tprelog 
I am totally new to Home Assistant and I was intensively searching for a working Google Play Music Media Player component for my home which is packed with ChromeCast resp. Google Home Mini devices and finally found THE solution for me here (in combination with miikkajo's gmusicproxy hassio addon though) for playing music all around my home.

What drives me on this whole topic is my intention to play music on specific speakers one day using Home Assistant REST API calls triggered by Raspberry Pi's RFID Readers. However this needed some preparation: My plan first of all was to have multiple music player / input selection card combinations aka your homeassistant-gmusic_player's (same as asked for by @pmcelreavy ).

I therefore needed to achieve an instantiation somehow. Luckily this did not mean too much changes to your media_player.py home assistant component code from my point of view. I have simply added the following two new variables right below your other CONF_* variable definition:

> CONF_SYNC_MEDIA = DOMAIN + '.sync_media'
CONF_PLAY_MEDIA = DOMAIN + '.play_media'

The reason for this addition was that I wanted to only change the DOMAIN variable upon any new instantiation. The domain name was repeated in the hass.bus.listen calls:

>hass.bus.listen('gmusic_player.sync_media', self._update_sources)
hass.bus.listen('gmusic_player.play_media', self._gmusic_play_media)

I have replaced those lines with the following:

>hass.bus.listen(config.get(CONF_SYNC_MEDIA), self._update_sources)
hass.bus.listen(config.get(CONF_PLAY_MEDIA), self._gmusic_play_media)

Time to speak about further details of my understanding of instantiation in this scope... For every new instance I perform the following steps:

- Think about a new DOMAIN name (e.g. 'gmusic_wife_player' or 'gmusic_kid_player')
- Copy the whole config/custom_components/gmusic_player folder according to a folder name that matches your new DOMAIN name (e.g. to config/custom_components/gmusic_wife_player or config/custom_components/gmusic_kid_player)
- Change the media_player.py DOMAIN variable in the newly created folder to the new DOMAIN name (e.g. 'gmusic_wife_player' or 'gmusic_kid_player')
- Copy the config/packages/gmusic_config.yaml file according to the desired DOMAIN name you selected before (e.g. config/packages/gmusic_wife_config.yaml or config/packages/gmusic_kid_config.yaml)
- Copy the config/packages/gmusic_player.yaml file according to the desired DOMAIN name you selected before (e.g. config/packages/gmusic_wife_player.yaml or config/packages/gmusic_kid_player.yaml)

The final step is then to perform changes to the newly created YAML file pairs.
Let's say your new DOMAIN is called 'gmusic_wife_player': Then your candidates for editing should be the 'gmusic_wife_config.yaml' and 'gmusic_wife_player.yaml' files located in your config/packages directory:

Changes to the gmusic_wife_config.yaml file:

- Replace the first 2 'gmusic_player' occurrences with 'gmusic_wife_player' (third occurrence is part of a link in a comment).
- Leave the credentials part as is (worked out for me accidentally!) or create new !secret defs (following the selected naming syntax e.g. gmusic_wife_username etc.).
- Edit the list of speakers to your needs or leave them as they are.
- Comment (put a hash '#' in front of) the gmusicproxy row (if used in your very first instance). Reason: I do not know or cannot imagine how it could handle more than 1 player -- I would be grateful for enlightenment :)

Changes to the gmusic_wife_player.yaml file:

- Find and replace any 'gmusic_' occurrences with 'gmusic_wife_' in gmusic_wife_player.yaml
- In the 'group' definition replace 'google_music_media_player' with 'google_music_wife_media_player'
- Replace 'name: Google Music' definition with 'name: Google Music Wife'

After restarting the Home Assistant you should be presented with 2 new working music player / input selection card entities - If I did not forget anything in my description.

Next steps will be the Home Assistant REST API part. I was able to set the input_select entities remotely already. But got no luck on triggering the music players -- Again I would be grateful for enlightenment :)

**Comment by tprelog** [comment]
@boomshkr 

So I kinda follow -- At least I see what your after - I haven't tried messing with the REST API so I can not offer any help at the moment. Did you happen to try using the REST API before you modified and added multiple instantiations? Do the multiple instantiations work from the HA GUI?

I'll need to play around with the REST API before I can offer any help to that

Do you know I have added `script.gmusic_play_media` -- It will set the required input_selects, including the speakers and start playback -- Would it be easier to trigger this using the REST API with the proper payload.

![image](https://user-images.githubusercontent.com/35702532/76694290-69164600-6647-11ea-9a6f-282e547bd2d2.png)


---

> * Leave the credentials part as is (worked out for me accidentally!)

Even with multiple gmusic instantiations -- Each account can only stream music to one device at a time. This is working in gmusic_player because you are using gmusicproxy to stream music -- gmusic_player at this point is not doing any streaming. The one device limit is a restriction set by Google so the same applies to gmusicproxy but because of the way gmusicproxy works it may somehow seem to get around this.

> or create new !secret defs (following the selected naming syntax e.g. gmusic_wife_username etc.)

You need to this if gmusic_player_wife is a different account but there is nothing gained if your using the same account across all your instantiations

So on those lines, if you are using the same account across all instantiations, I'm not sure you would need to create multiple instantiations because (unless gmusicproxy is somehow getting around this) you can still only stream to one device at a time. In other words, gmusicproxy can not _continuously_ stream music to _both_ gmusic_player and gmusic_player_wife at the same time, using the same account.



But not to neglect this...

> My plan first of all was to have multiple music player / input selection card combinations aka your homeassistant-gmusic_player's (same as asked for by @pmcelreavy )

So was I thinking the correct way to do this would be somehow leveraging a Home Assistant user and then gmusic_player could spawn its own new instantiation, somehow separate for each user.

You have me thinking here though, even if it's not the best way to go about this, I might be able to make it somewhat easier (or at least maybe less edits) to add multiple instantiations by following your approach.

**Comment by boomshkr** [comment]
@tprelog 

Thanks for your answer! The following screenshots should further explain my setup. I have got 4 running instances running in parallel currently. Every instance consists of the following 3 entities each:

1. Home assistant group resulting in a card (e.g. `group.google_music_media_player`) with the following entities:
- `media_player.gmusic_player`
- `script.gmusic_sync_media`
- `input_select.gmusic_player_speakers`
- `input_select.gmusic_player_source`
- `input_select.gmusic_player_playlist`
- `input_select.gmusic_player_station`

2. Home assistant media player entity (e.g. `media_player.gmusic_player`)

3. Google Home Mini device media player entity (e.g. `media_player.nest_hub`)

Only the first entity references the gmusicproxy URI (like http://<gmusicproxy_ip>:9999):
- `gmusicproxy: !secret gmusic_proxy`

The other 3 instance's configuration have their gmusicproxy comments like:
- `# gmusicproxy: !secret gmusic_proxy`

My current example is just a test and I will most likely reduce the amount of instances to 3 in which only 2 instances (for my kids) should be remotely controlled by Rapsberry PI RFID readers, whereas I sometime might actively control the remainig 1 instance for my own purpose (via the Home assistant Web UI).

Now here is how it looks and works currently, while all 4 instances use the same credentials, which is weird. First off the `custom_components` and `packages` files and directories:

**config/custom_components:**

![2020-03-15 11_41_47-custom_components](https://user-images.githubusercontent.com/62095556/76701858-517da280-66c5-11ea-9ff5-2443dcaa6480.png)

**config/packages:**

![2020-03-15 11_36_46-packages](https://user-images.githubusercontent.com/62095556/76701869-740fbb80-66c5-11ea-8467-def443f7ec52.png)

**Home Assistant Overview** (playing even the same playlist shuffled in parallel):

![2020-03-15 11_05_59-Home Assistant](https://user-images.githubusercontent.com/62095556/76701877-825dd780-66c5-11ea-9473-6f9c6b60f1c8.png)

Unfortunately your advice on triggering the `script.gmusic_play_media` via the Developer Tools > SERVICES dialogue does not work for me: Nothing happens although I have set all values to data known by the Home Assistant. Is it working on your side? I have the feeling that it is not enough to only trigger the `script.gmusic_play_media` -- One might need to turn on the according device maybe - but not sure... still fiddling around.

However I was already able to remotely change the playlist for specific groups or cards already. Here is a working example triggered from the Developer Tools > SERVICES dialogue:

![2020-03-15 14_15_51-Home Assistant](https://user-images.githubusercontent.com/62095556/76702188-3ceed980-66c8-11ea-81c7-00bf261527a0.png)

If I would find the magic of triggering the according media player as a next step I would be so grateful.

**Comment by boomshkr** [comment]
@tprelog 
Finally - I have found a way to finalize my solution of being able to trigger your gmusic_player component's media player via REST API calls with `curl` which might now easily being scripted! So this comment will be interesting for @pmcelreavy now, too, I bet.

First of all you need to **activate the api integration** which exposes a RESTful API and allows one to interact with the Home Assistant instance that is running headless by adding the api component to my **configuration.yaml** file with the following one-liner:

`api:`

Afterwards we need 2 additional Home Assistant automations of trigger type 'webhook' to turn on/off your gmusic_player. Webhook triggers are triggered by web requests made to the webhook endpoint: `/api/webhook/<webhook_id>`. I have added the following code right at the end of the `automation old:` section in your **gmusic_player.yaml**:

```yaml
  - alias: gmusic_player_turn_on
    initial_state: 'on'
    description: 'gmusic_player turn_on webhook'
    trigger:
    - platform: webhook
      webhook_id: gmusic_player_turn_on
    condition: []
    action:
    - entity_id: media_player.gmusic_player
      service: media_player.turn_on

  - alias: gmusic_player_turn_off
    initial_state: 'on'
    description: 'gmusic_player turn_off webhook'
    trigger:
    - platform: webhook
      webhook_id: gmusic_player_turn_off
    condition: []
    action:
    - entity_id: media_player.gmusic_player
      service: media_player.turn_off
```

Your gmusic_player media_player component's **turn_on** and **turn_off** definitions are already packed with all functions needed - which is so nice (!) - we just have to fire them up.

But before one might want to pre-select the speakers and playlist to any of their known options remotely first...

**Setting the gmusic_player_speakers to 'bedroom_mini':**
```shell
curl -X POST -H "Authorization: Bearer ABCDEFGH" -H "Content-Type: application/json" -d '{"entity_id": "input_select.gmusic_player_speakers", "option": "bedroom_mini"}' http://IP_ADDRESS:8123/api/services/input_select/select_option
```

**Setting the gmusic_player_playlist to 'Country Hits':**
```shell
curl -X POST -H "Authorization: Bearer ABCDEFGH" -H "Content-Type: application/json" -d '{"entity_id": "input_select.gmusic_player_playlist", "option": "Country Hits"}' http://IP_ADDRESS:8123/api/services/input_select/select_option
```

**Now to the real magic**: Webhook endpoints do not require authentication besides knowing the webhook id. Those remote REST calls are shorter - so let's fire them up:

**Turning on the gmusic_player:**
```shell
curl -X POST -H "Content-Type: application/json" -d {} http://IP_ADDRESS:8123/api/webhook/gmusic_player_turn_on
```

**Turning off the gmusic_player:**
```shell
curl -X POST -H "Content-Type: application/json" -d {} http://IP_ADDRESS:8123/api/webhook/gmusic_player_turn_off
```
Hope this helps to move forward with this beautiful project.

**Comment by tprelog** [comment]
@boomshkr -- I'm glad to see you are making progress here!

> Unfortunately your advice on triggering the `script.gmusic_play_media` via the Developer Tools > SERVICES dialogue does not work for me: Nothing happens although I have set all values to data known by the Home Assistant. Is it working on your side? I have the feeling that it is not enough to only trigger the `script.gmusic_play_media` -- One might need to turn on the according device

**Yes `script.gmusic_play_media` works via the Developer Tools > SERVICES.**
 

---


I've followed your steps to enable RESTful API and did a few tests. Your examples using curl made this much easier to just jump in. I have also tested `script.gmusic_play_media` based on your examples. 

_This is exactly what `script.gmusic_play_media` is meant for_ :wink: 

#### Using Authentication ( no additional automations required )
- Set gmusic_player_speakers to 'bedroom_mini'
- Set gmusic_player_source to 'Playlist'
- Set gmusic_player_playlist to 'Country Hits'
- Turn on gmusic_player

```
curl -X POST -H "Authorization: Bearer ABCDEFGH" -H "Content-Type: application/json" -d '{"speakers": "bedroom_mini", "source": "playlist", "name": "Country Hits"}' http://IP_ADDRESS:8123/api/services/script/gmusic_play_media
```
#### Turning off the gmusic_player
```
curl -X POST -H "Authorization: Bearer ABCDEFGH" -H "Content-Type: application/json" -d '{"entity_id": "media_player.gmusic_player"}' http://IP_ADDRESS:8123/api/services/media_player/turn_off
```

---

#### Using the "webhook" automation ( no authentication required )
- Set gmusic_player_speakers to 'bedroom_mini'
- Set gmusic_player_source to 'Playlist'
- Set gmusic_player_playlist to 'Country Hits'
- Turn on gmusic_player

```
automation:
  - alias: gmusic_play_country_hits
    initial_state: 'on'
    description: 'gmusic_play_country_hits webhook'
    trigger:
    - platform: webhook
      webhook_id: gmusic_play_country_hits
    condition: []
    action:
      - service: script.gmusic_play_media
        data:
          name: Country Hits
          source: playlist
          speakers: bedroom_mini

```

#### Trigger (turn on) gmusic_player Country Hits
```
curl -X POST -H "Content-Type: application/json" -d {} http://IP_ADDRESS:8123/api/webhook/gmusic_play_country_hits
```

**Comment by boomshkr** [comment]
@tprelog -- Thanks for your inspiration! You know what? Your `script.gmusic_play_media` simply stopped working for me since my very first change in your `media_player.py` file:

Somehow your script did not like my changes (fully described in my first comment) at all:

```python
CONF_SYNC_MEDIA = DOMAIN + '.sync_media'
CONF_PLAY_MEDIA = DOMAIN + '.play_media'
```
(...)
```python
hass.bus.listen(config.get(CONF_SYNC_MEDIA), self._update_sources)
hass.bus.listen(config.get(CONF_PLAY_MEDIA), self._gmusic_play_media)
```
So I have reverted back to the original lines and removed my CONF_SYNC_MEDIA and CONF_PLAY_MEDIA variables right below your other CONF_* variable definitions and re-established:

```python
hass.bus.listen('gmusic_player.sync_media', self._update_sources)
hass.bus.listen('gmusic_player.play_media', self._gmusic_play_media)
```
So that was why I could not manage to get the `script.gmusic_play_media` utilized the whole time I was developing my plans! Sorry for all the confusion!!! But I am still a beginner with the Home Assistant suite...

However with your help and some further testing I finally figured it out the way I would prefer this whole thing to function. I wanted to be able to POST a JSON payload for `speakers`, `source` and `name` variables through my `gmusic_player_turn_on` webhook to your `script.gmusic_play_media` script.

I fully agree on your described approach where there is no additional automations required (using the `script.gmusic_play_media` entity and `media_player.turn_off` service with authentication. Works like a charm -- But I was still concerned with the further development of the "webhook" option and ended up with the following which I wanted to share with you:

**Using the "webhook" automation to play music ( no authentication required )** - enhanced!
- Set gmusic_player_speakers to 'bedroom_mini'
- Set gmusic_player_source to 'Playlist'
- Set gmusic_player_playlist to 'Country Hits'
- Turn on gmusic_player

**Automation gmusic_player_turn_on:**
```yaml
  - alias: gmusic_player_turn_on
    initial_state: 'on'
    description: 'gmusic_player_turn_on webhook'
    trigger:
    - platform: webhook
      webhook_id: gmusic_player_turn_on
    condition: []
    action:
    - service: script.gmusic_play_media
      data_template:
        speakers: "{{ trigger.json.speakers }}"
        source: "{{ trigger.json.source }}"
        name: "{{ trigger.json.name }}"
```
**Trigger (turn on) gmusic_player with JSON payload to set values**
```bash
curl -X POST -H "Content-Type: application/json" -d '{"speakers": "bedroom_mini", "source": "playlist", "name": "Country Hits"}' http://IP_ADDRESS:8123/api/webhook/gmusic_player_turn_on
```

**Using the "webhook" automation to stop music ( no authentication required )**
- Turn off gmusic_player

**Automation gmusic_player_turn_off:**
```yaml
  - alias: gmusic_player_turn_off
    initial_state: 'on'
    description: 'gmusic_player turn_off webhook'
    trigger:
    - platform: webhook
      webhook_id: gmusic_player_turn_off
    condition: []
    action:
    - entity_id: media_player.gmusic_player
      service: media_player.turn_off
```

**Turning off the gmusic_player:**
```bash
curl -X POST -H "Content-Type: application/json" -d {} http://IP_ADDRESS:8123/api/webhook/gmusic_player_turn_off
```

So this whole topic of remote controlling your `gmusic_player` component is fully clear to me now -- both the authentication and non-authentication method. Thanks so much!

**Comment by tprelog** [comment]
@boomshkr 

> **Using the "webhook" automation to play music ( no authentication required )** - enhanced!

Outstanding! These are great examples using both RESTful API and `script.gmusic_play_media`

I'll likely update [this post in the Home Assistant forum](https://community.home-assistant.io/t/google-music-in-ha-now-as-a-media-player/119918?u=troy) to include these examples.

Do you have an account on the HA forums? I would like to tag your username with credit




> Somehow your script did not like my changes (fully described in my first comment) at all:

I figured this would be an issue. I will look at some code changes to try getting multiple instances to work. This could also be useful for people who want to connect multiple accounts

**Comment by boomshkr** [comment]
@tprelog My HA forums user name is the same as here. Thanks man!

**Comment by boomshkr** [comment]
I just thought it would be a good idea to conclude what has been achieved with **webhooks** here in a more copy-and-paste-like style for the whole community.

Also my previous automation was still an addition to your gmusic_player package code, which I did not like. With the following snippets there are **no code changes** needed to this project at all.

I am assuming that you are [splitting the home assistant configuration](https://www.home-assistant.io/docs/configuration/splitting_configuration/) for your different components - which makes perfect sense anyway - and should also include a specific file for your `automation` section then. Let's call it `automations.yaml`.

Make sure to have added (or make sure to add) the following line to your **configuration.yaml**:
```yaml
automation: !include automations.yaml
```

Webhook automations for gmusic_player **automations.yaml**:
```yaml
- id: gmusic_player_turn_on
  alias: gmusic_player_turn_on
  description: gmusic_player turn_on webhook
  trigger:
  - platform: webhook
    webhook_id: gmusic_player_turn_on
  condition: []
  action:
  - data:
      name: '{{ trigger.json.name }}'
      source: '{{ trigger.json.source }}'
      speakers: '{{ trigger.json.speakers }}'
    data_template:
      name: '{{ trigger.json.name }}'
      source: '{{ trigger.json.source }}'
      speakers: '{{ trigger.json.speakers }}'
    service: script.gmusic_play_media
  initial_state: 'on'

- id: gmusic_player_turn_off
  alias: gmusic_player_turn_off
  description: gmusic_player turn_off webhook
  trigger:
  - platform: webhook
    webhook_id: gmusic_player_turn_off
  condition: []
  action:
  - data: {}
    entity_id: media_player.gmusic_player
    service: media_player.turn_off
  initial_state: 'on'
```

**Turning on gmusic_player** incl. JSON payload to pre-select values via **curl** command line tool:
```bash
curl -X POST -H "Content-Type: application/json" -d '{"speakers": "bedroom_mini", "source": "playlist", "name": "Country Hits"}' http://IP_ADDRESS:8123/api/webhook/gmusic_player_turn_on
```

**Turning off gmusic_player** via **curl** command line tool:
```bash
curl -X POST -H "Content-Type: application/json" -d {} http://IP_ADDRESS:8123/api/webhook/gmusic_player_turn_off
```
Enjoy!

**Comment by tprelog** [comment]
> I am assuming that you are [splitting the home assistant configuration](https://www.home-assistant.io/docs/configuration/splitting_configuration/) for your different components - which makes perfect sense anyway

I completely agree! That is exactly why [I use packages to configure this component](https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder).

So you can take advantage here -- _**This is not required!**_

> Make sure to have added (or make sure to add) the following line to your **configuration.yaml**:
> 
> ```yaml
> automation: !include automations.yaml
> ```

**Create a new package file instead**
For Example - You can simply add a new file `packages/gmusic_webhooks.yaml`
```
## Webhook automations for gmusic_player
automation:
  - id: gmusic_player_turn_on
    alias: gmusic_player_turn_on
    description: gmusic_player turn_on webhook
    trigger:
    - platform: webhook
      webhook_id: gmusic_player_turn_on
    condition: []
    action:
    - data:
        name: '{{ trigger.json.name }}'
        source: '{{ trigger.json.source }}'
        speakers: '{{ trigger.json.speakers }}'
      data_template:
        name: '{{ trigger.json.name }}'
        source: '{{ trigger.json.source }}'
        speakers: '{{ trigger.json.speakers }}'
      service: script.gmusic_play_media
    initial_state: 'on'

  - id: gmusic_player_turn_off
    alias: gmusic_player_turn_off
    description: gmusic_player turn_off webhook
    trigger:
    - platform: webhook
      webhook_id: gmusic_player_turn_off
    condition: []
    action:
    - data: {}
      entity_id: media_player.gmusic_player
      service: media_player.turn_off
    initial_state: 'on'
```

**Comment by tprelog** [comment]
> a more copy-and-paste-like style for the whole community.

How about something like this instead :smile:

###  **Introducing community addons for gmusic player!** :tada:

**Webhook automations for gmusic_playe by @boomshkr**

_Install_ -- add this package.yaml to `homeassistant/packages`

```
#-----------------------------------------------------------
# -- gmusic_webhooks.yaml -- by @boomshkr 
# -- Trigger gmusic_player using webhooks --
#-----------------------------------------------------------

automation:
  - id: gmusic_player_turn_on
    alias: gmusic_player_turn_on
    description: gmusic_player turn_on webhook
    trigger:
    - platform: webhook
      webhook_id: gmusic_player_turn_on
    condition: []
    action:
    - data:
        name: '{{ trigger.json.name }}'
        source: '{{ trigger.json.source }}'
        speakers: '{{ trigger.json.speakers }}'
      data_template:
        name: '{{ trigger.json.name }}'
        source: '{{ trigger.json.source }}'
        speakers: '{{ trigger.json.speakers }}'
      service: script.gmusic_play_media
    initial_state: 'on'

  - id: gmusic_player_turn_off
    alias: gmusic_player_turn_off
    description: gmusic_player turn_off webhook
    trigger:
    - platform: webhook
      webhook_id: gmusic_player_turn_off
    condition: []
    action:
    - data: {}
      entity_id: media_player.gmusic_player
      service: media_player.turn_off
    initial_state: 'on'
```



**Turning on gmusic_player via curl command line tool:**
- Use JSON payload to pre-select values
```
curl -X POST -H "Content-Type: application/json" -d '{"speakers": "bedroom_mini", "source": "playlist", "name": "Country Hits"}' http://IP_ADDRESS:8123/api/webhook/gmusic_player_turn_on
```

**Turning off gmusic_player via curl command line tool:**
```
curl -X POST -H "Content-Type: application/json" -d {} http://IP_ADDRESS:8123/api/webhook/gmusic_player_turn_off
```
