### ISSUE TITLE
Issue with v0.2.0

### ISSUE THREAD

**Issue by kaizersoje** [tprelog/homeassistant-gmusic_player#9]
After upgrading to v0.2.0, I keep getting the errors below.

Error while setting up gmusic_player platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gmusic_player/media_player.py", line 122, in setup_platform
    add_devices([GmusicComponent(hass, config)])
  File "/config/custom_components/gmusic_player/media_player.py", line 177, in __init__
    with open(_authtoken, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.homeassistant/.gmusic_authtoken'

**Comment by tprelog** [comment]
Hello


> FileNotFoundError: [Errno 2] No such file or directory: '/root/.homeassistant/.gmusic_authtoken'

Sorry about that -- I had made a change to the `DEFAULT_TOKEN_PATH` in v0.2.0.
 
_I have since reverted this change._

Please update to v0.2.1 and it should correct the error

**Comment by kaizersoje** [comment]
I have v0.2.1 installed. However, I still keep getting the error.

**Comment by tprelog** [comment]
:thinking: I'm not sure why that's not working then.

You can also set the token (dir) path in `gmusic_config.yaml` 

I recommend to use you Home Assistant configuration directory
 
---

For example if you're using ( formerly known as ) Hass.io then you would set `token_path: /config/.`
 ( The trailing  "`.`" will make the file hidden in the directory )

example
```yaml
## Google Music Media Player
## gmusic_config.yaml

media_player:
  - platform: gmusic_player
    device_id: !secret gmusic_device_id
    username: !secret gmusic_username
    password: !secret gmusic_password
    speakers: # media_players
      - bedroom_stereo
      - workshop_stereo
    gmusicproxy: !secret gmusic_proxy
    token_path: /config/.
```
